// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MapMarkerKitDemo",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "MapMarkerKitDemo",
            targets: ["AppModule"],
            bundleIdentifier: "net.pilaski.mapmarkerkitdemo",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .map),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        // The floor is the version this demo actually needs, not the oldest
        // that once worked. It sat at 0.0.2 while the demo grew, so when the
        // marker views gained `showsBadge` the range quietly resolved 0.0.10
        // and the demo failed to build with "Extra argument 'showsBadge' in
        // call" — an error about the package, reported against the demo.
        //
        // Raise this whenever the demo starts using something new. The pin is
        // a URL rather than a relative path because this example is copied to
        // an iPad on its own, with no repository around it.
        .package(url: "https://github.com/pilaski/MapMarkerKit.git", "0.0.11"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "MapMarkerKit", package: "MapMarkerKit")
            ],
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
